# Generated by Django 5.0.6 on 2024-07-12 12:43

import django.db.models.deletion
import utils.base_model
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("professional", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PersonalHealthRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="UUID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "full_name",
                    models.CharField(max_length=255, verbose_name="Full Name"),
                ),
                (
                    "picture",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=utils.base_model.get_upload_path,
                        verbose_name="Picture",
                    ),
                ),
                ("age", models.IntegerField(verbose_name="Age")),
                ("locality", models.CharField(max_length=100, verbose_name="Locality")),
                ("street", models.CharField(max_length=100, verbose_name="Street")),
                (
                    "reference",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Reference"
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Phone Number",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        unique=True,
                        verbose_name="E-mail",
                    ),
                ),
                (
                    "household_size",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Household Size"
                    ),
                ),
                (
                    "health_issue",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Health Issue",
                    ),
                ),
                (
                    "symptoms",
                    models.TextField(
                        blank=True, max_length=530, null=True, verbose_name="Symptoms"
                    ),
                ),
                (
                    "last_recorded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="professional.professional",
                    ),
                ),
            ],
            options={
                "verbose_name": "Personal Health Record",
                "verbose_name_plural": "Personal Health Records",
                "ordering": ["-created_at"],
            },
        ),
    ]
